---
- hosts: all
  vars:
         ansible_python_interpreter: "/usr/bin/python3"
 
  tasks:
    - name: Start service
      shell: sudo docker-compose -f /var/lib/jenkins/workspace/ProjetoIII_master-RIIQQCSH57GWCVSXSFF23DWD5M4D34Q7KPYW67VQRZGOWEJNAQFQ/docker/wordpress/docker-compose.yml up -d
